### ISSUE TITLE
YHOO weather make request return nil

### ISSUE THREAD

**Issue by luson1201** [yahoo/TDOAuth#31]
I use TDOAuth make nsmutable request, return Nil can tell me how to solve it?
The following method request returns nil .
consumerKey ，consumerSecret，appId All have value。

-(NSMutableURLRequest *)requestWithParameters:(NSDictionary *)parameters
{
    
    NSMutableURLRequest *request = [[TDOAuth URLRequestForPath:@"/forecastrss"
                                                 GETParameters:parameters
                                                        scheme:@"https"
                                                          host:@"weather-ydn-yql.media.yahoo.com"
                                                   consumerKey:self.consumerKey
                                                consumerSecret:self.consumerSecret
                                                   accessToken:nil
                                                   tokenSecret:nil] mutableCopy];
    [request addValue:self.appId forHTTPHeaderField:@"X-Yahoo-App-Id"];
    return request;
}

**Comment by adamkaplan** [comment]
@luson1201 If you are still having this issue, can you try it again with 1.4.1? Complete rewrite fixed many bugs
